### ISSUE TITLE
Project zomboid World player DB

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#12]
kills the data base, making unreadable by the server, fixed by deleting the database.

**Comment by SalSevenSix** [comment]
What exactly was done that caused an issue with the PZ player.db ?

**Comment by maxtraxv3** [comment]
i pressed the clear "World player DB" button then restarted, then was not able to wright to it, im changed all permissions via ftp atm see if its Pterodactyl changing file permissions, even tho it set to allow.

**Comment by maxtraxv3** [comment]
i guess some weird shit with Pterodactyl or Docker
![image](https://github.com/SalSevenSix/serverjockey/assets/12743527/39898454-36b9-4b85-b54b-efa9a488042b)

LOG  : General     , 1688809254946> 20,291,522> user database "/home/container/modded_server_not_easy_mode/world/db/servertest.db"
ERROR: General     , 1688809255092> 20,291,667> No space left on device

server only using 12gigs out of 80gigs i gave it every thing set to unlimited restart multiable times, no idea whats not letting it wright.
![image](https://github.com/SalSevenSix/serverjockey/assets/12743527/e7542d5b-5e79-4813-a4e2-90ca6d11b06a)
![image](https://github.com/SalSevenSix/serverjockey/assets/12743527/9da53dc7-1cb4-4162-8610-2b0132fc9ea3)

**Comment by maxtraxv3** [comment]
fuck it im go back just ubuntu.

**Comment by SalSevenSix** [comment]
"No space left on device"

Ah ok. This is a known issue with PZ dedicated server on Docker. The automatic backups that the server does use file operations that Docker prohibits. You need to disable those backups in the INI file, then delete any existing backups that were made.

Problem has nothing to do with player DB or ServerJockey

**Comment by maxtraxv3** [comment]
why would dock want to stop that? well whatever.

**Comment by SalSevenSix** [comment]
I have no idea. It's something about the backup process Docker doesn't like. It renames all the previous backups. Maybe it's doing it in an unusual way.

https://theindiestone.com/forums/index.php?/topic/49783-javautilconcurrentexecutionexception-javaioioexception-no-space-left-on-device/

Seen the issue myself on a large gaming community that uses Ptero. The workaround as I said is delete the backups, disable all of them them in the INI file, then restart the container and it should work.
