### ISSUE TITLE
Installing RunTime with an account token?

### ISSUE THREAD

**Issue by circularwaffle** [SalSevenSix/serverjockey#15]
I've got serverjockey up and running and seemingly ready to go...

However, I have a heavily modded (but tested) server config that requires a steam login. I have a server token to use. However, I'm unsure if I can change the options for "Installing a RunTime" to include a non-anonymous install. 

Hoping this makes sense. Whenever you can, if you have any ideas. Thanks!!!!!!

**Comment by SalSevenSix** [comment]
If this is Project Zomboid, the dedicated server is downloaded anonymously. How does the modlist require a steam login to download? Never seen that before.

If you must directly access to the PZ dedicated server (runtime), after installing it you can create a backup using the backup runtime feature. Download and unpack the zip. Manually add mods you download. Zip, upload and restore it.

**Comment by circularwaffle** [comment]
Yes, this is for Project Zomboid.

And that's not the first time someone has told me that. The only thing I can find is that apparently at some point, there was some change that ultimately ended up requiring the steamcmd app installs have entitlement to a game before being able to download and install *some* mods from the steam community. I can download most mods on to my server. But, some of them just error out and fail when I try to install them (with an anonymously logged in zomboid install via steamcmd). Once I use steamcmd authenticated into my steam account (where I own PZ), it's cool with it and downloads ALL mods to my server. Just for reference, though...our server has ~540 mods currently.

Besides all that - Thank you for your reply. I will try that out :)

**Comment by maxtraxv3** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2800420113 <-- guide to adding mods for server config file.
witch you access every easly via the editor after you made a server instance.
the quick verson is on every workshop page there workshop id and mod id you need to add that to servertest.ini

your expecting a steam server witch is mad for LAN not a dedicated server.
if you want to set it up that way you need to run windows and make a new user account for steam and have steam personal "server" with windows, you will have to restart this every day,
ive ran serverjoky with 300+ mods on zombied.

**Comment by circularwaffle** [comment]
All good. I've got it working outside of my LAN with your suggestions.
Thanks!
