### ISSUE TITLE
Create lastest tag on DockerHub

### ISSUE THREAD

**Issue by Maickeenn** [SalSevenSix/serverjockey#17]
Having a latest tag on DockerHub is beneficial for several reasons:

  1. Ease of Use: Users can pull the most recent stable version of the Docker image without needing to know the specific version number.
  2. Consistency: It ensures consistency across different environments and simplifies the deployment process, as users can always reference latest for the most current version.
  3. Automation: Many CI/CD pipelines and deployment scripts rely on the latest tag to fetch the most recent image. This minimizes manual intervention and reduces the chance of human error.
  4. Community Standard: It follows a common practice in the Docker community, making our project more user-friendly and aligning with industry standards.

Steps to Create the Latest Tag:

1. Build the Docker Image:
Ensure that you have the Dockerfile set up correctly and that the build process is tested.
```
docker build -t yourusername/serverjockey:latest .
```

2. Tag the Docker Image:
If the image is already built and tagged with a version, retag it as latest.

```
docker tag yourusername/serverjockey:current_version yourusername/yourimage:latest
```

3. Push the Latest Tag to DockerHub:
Authenticate with DockerHub and push the latest tag.

```
docker login
docker push yourusername/serverjockey:latest
```

4. Update Documentation:
Ensure that the README and any relevant documentation are updated to inform users about the latest tag.
Add instructions on how to pull the latest image:
```
docker pull yourusername/serverjockey:latest
```

**Comment by SalSevenSix** [comment]
Done
