### ISSUE TITLE
discord bot you skiped a step, in setup.

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#3]
followed all steps, looked up up and down billion times.
![image](https://user-images.githubusercontent.com/12743527/193475561-250135e5-e19d-4b59-9d61-475675c08201.png)

by default these are off, if they are off the bot cant reply.

**Comment by SalSevenSix** [comment]
Looks like discord has changed. I checked the bot I created for the demo. I didn't need to changes settings, but "Message Content Intent" is ON.
![Screenshot from 2022-10-03 15-12-28](https://user-images.githubusercontent.com/71133311/193500497-f6857316-a548-4cf2-b9ab-08eff58199bc.png)
I will update the guide in the webapp.

**Comment by maxtraxv3** [comment]
yeah they do it alot when comes to bot unfortunately.

**Comment by SalSevenSix** [comment]
Updated instructions. Committed to develop branch.
![Screenshot from 2022-10-03 18-16-10](https://user-images.githubusercontent.com/71133311/193521599-3b474f1d-54fd-45b8-8e9b-1db5f54fdade.png)
