### ISSUE TITLE
auto restart option?

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#6]
any chance of auto restart server function?
and a toggle switch for the setting?

**Comment by maxtraxv3** [comment]
also there gotta be a better way to update the server.
or at lest make it clearer to people who wouldn't understand.

**Comment by SalSevenSix** [comment]
If you use the "daemon" option to start the server then it will automatically be restarted if it crashes.
As for updating the game server, just Install Runtime again.

**Comment by maxtraxv3** [comment]
ah thanks
