### ISSUE TITLE
server update?!?

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#7]
had to "install runtime" because server wouldn't update to 41.77.4 from 41.77.3

redownloading all the mod again isnt a good feature, is there away to get a back up of them as well that i can reupload?

**Comment by SalSevenSix** [comment]
The webservice takes a param to delete the existing runtime before installing. However both webapp and discord clients flag to delete it. However I can change that to allow the user to specify.

**Comment by SalSevenSix** [comment]
Fixed in Version 0.0.4. Install Runtime doesn't delete the existing install before new install. Webapp allows you to delete the existing install if you want a fresh install.
