### ISSUE TITLE
if you upload via discord !setconfig ini and !setconfig sandbox Spawn Regions and Spawn Points stay blank

### ISSUE THREAD

**Issue by maxtraxv3** [SalSevenSix/serverjockey#8]
if you upload via discord !setconfig ini and !setconfig sandbox before you run the server for the first time, Spawn Regions and Spawn Points stay blank and arnt read.

ima try restart(the pc) see if this fixes this, just making you aware of this.

**Comment by maxtraxv3** [comment]
![image](https://user-images.githubusercontent.com/12743527/205659605-fbb2f84d-8e49-4923-8893-b699c9e6cfc8.png)
nope still stay blank.

reload does nothing as well.

**Comment by maxtraxv3** [comment]
so turns out there both blank or didnt generate the files, login the game force spawn me randomly.

**Comment by maxtraxv3** [comment]
seem when i updated ubuntu to the newest version your program lost the ablity to wright some files?
map mods no longer work as well, and setting keep resetting as being changed, expect some thing do save and change..??
i dunno.

**Comment by SalSevenSix** [comment]
I think if you specify the INI and Sandbox config files, the PZ Server doesn't write default Spawn config files.

**Comment by SalSevenSix** [comment]
In recent testing I can confirm that the PZ Server itself doesn't generate Spawn config files if you set INI and Sandbox config files.
